[build-system]
requires = ["setuptools>=61.0", "setuptools-scm>=8", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tentaclio-postgres"
dynamic = ["version"]
description = "A python project containing all the dependencies for schema postgres for tentaclio."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    {name = "Octopus Energy", email = "nerds@octopus.energy"}
]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "tentaclio",
    "psycopg2-binary",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "black",
    "flake8",
    "Flake8-pyproject",
    "isort>=5.11.2",
    "mypy",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["*tentaclio_postgres*"]

[tool.setuptools_scm]
fallback_version = "0.0.0"

[tool.black]
line-length = 99
include = '\.pyi?$'
exclude = '(\.mypy_cache)'

[tool.flake8]
exclude = ["logs", ".*/*.py", "*.egg-info"]
max-line-length = 99
max-complexity = 10
ignore = ["F405","W391","W503", "E704"]

[tool.isort]
profile = "black"
line_length = 99
multi_line_output = 3
include_trailing_comma = true
default_section = "THIRDPARTY"
known_first_party = ["tentaclio_postgres"]
sections = "STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"

[tool.mypy]
incremental = "True"
warn_unused_configs = "True"
warn_unused_ignores = "True"
check_untyped_defs = "True"
warn_redundant_casts = "True"
ignore_missing_imports = "True"
