---
# Python CircleCI 2.0 configuration file
#
# INFO: Check CircleCI documentation for more details
#       https://circleci.com/docs/2.0/language-python/

version: 2.1

executors:
  standard:
    docker:
      - image: cimg/python:3.10

# -----------------
# Reusable commands
# -----------------

commands:
  configure_github:
    steps:
      - run:
          name: Configure Github access
          command: |
            git config --global --unset url.ssh://git@github.com.insteadof;\
            echo https://${GITHUB_TOKEN}:@github.com > ~/.git-credentials
            git config --global credential.helper store

  checkout_source:
    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}-
            - source-
      - checkout:
          method: full
      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - "./.git"

  update_virtualenv:
    steps:
      - restore_cache:
          keys:
            - virtualenv-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "uv.lock" }}
            - virtualenv-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
            - virtualenv-{{ .Environment.CACHE_VERSION }}-
      - configure_github
      - run:
          name: Install Python packages
          command: make sync
      - save_cache:
          key: virtualenv-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "uv.lock" }}
          paths:
            - "./.venv"

jobs:
  lint:
    executor: standard
    steps:
      - checkout_source
      - update_virtualenv
      - run:
          name: Run Python linter
          command: make lint

  unit:
    executor: standard
    steps:
      - checkout_source
      - update_virtualenv
      - run:
          name: Run Python unit tests
          command: make unit

  functional:
    docker:
      - image: cimg/python:3.10
        environment:
          TENTACLIO__CONN__POSTGRES_TEST: postgresql://:@localhost:5432/tentaclio-db

      - image: cimg/postgres:18.4
        environment:
          # CircleCI img run under `circleci` user
          POSTGRES_USER: circleci
          POSTGRES_DB: tentaclio-db

    steps:
      - checkout_source
      - update_virtualenv
      - run:
          name: Run postgres functional tests
          command: make functional


workflows:
  version: 2

  test-build-deploy:
    jobs:
      - lint:
        filters:
          tags:
            only: /.*/
      - unit:
          filters:
            tags:
              only: /.*/
      - functional:
          filters:
            tags:
              only: /.*/
